import { Team } from '../types/simulator';

// 32 World Cup 2026 qualified nations with approximate FIFA-based strength ratings
export const NATIONS: Team[] = [
  { id: 'arg', name: 'Argentina',    flag: '🇦🇷', strength: 91 },
  { id: 'bra', name: 'Brazil',       flag: '🇧🇷', strength: 88 },
  { id: 'fra', name: 'France',       flag: '🇫🇷', strength: 87 },
  { id: 'spa', name: 'Spain',        flag: '🇪🇸', strength: 86 },
  { id: 'eng', name: 'England',      flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', strength: 85 },
  { id: 'ger', name: 'Germany',      flag: '🇩🇪', strength: 84 },
  { id: 'por', name: 'Portugal',     flag: '🇵🇹', strength: 84 },
  { id: 'ned', name: 'Netherlands',  flag: '🇳🇱', strength: 83 },
  { id: 'bel', name: 'Belgium',      flag: '🇧🇪', strength: 82 },
  { id: 'ita', name: 'Italy',        flag: '🇮🇹', strength: 82 },
  { id: 'cro', name: 'Croatia',      flag: '🇭🇷', strength: 80 },
  { id: 'uru', name: 'Uruguay',      flag: '🇺🇾', strength: 79 },
  { id: 'den', name: 'Denmark',      flag: '🇩🇰', strength: 79 },
  { id: 'mor', name: 'Morocco',      flag: '🇲🇦', strength: 78 },
  { id: 'col', name: 'Colombia',     flag: '🇨🇴', strength: 78 },
  { id: 'swi', name: 'Switzerland',  flag: '🇨🇭', strength: 78 },
  { id: 'tur', name: 'Türkiye',      flag: '🇹🇷', strength: 76 },
  { id: 'jpn', name: 'Japan',        flag: '🇯🇵', strength: 76 },
  { id: 'sen', name: 'Senegal',      flag: '🇸🇳', strength: 75 },
  { id: 'usa', name: 'USA',          flag: '🇺🇸', strength: 74 },
  { id: 'aut', name: 'Austria',      flag: '🇦🇹', strength: 74 },
  { id: 'mex', name: 'Mexico',       flag: '🇲🇽', strength: 73 },
  { id: 'kor', name: 'South Korea',  flag: '🇰🇷', strength: 73 },
  { id: 'ser', name: 'Serbia',       flag: '🇷🇸', strength: 72 },
  { id: 'nga', name: 'Nigeria',      flag: '🇳🇬', strength: 72 },
  { id: 'pol', name: 'Poland',       flag: '🇵🇱', strength: 71 },
  { id: 'can', name: 'Canada',       flag: '🇨🇦', strength: 70 },
  { id: 'ecua', name: 'Ecuador',     flag: '🇪🇨', strength: 69 },
  { id: 'aus', name: 'Australia',    flag: '🇦🇺', strength: 68 },
  { id: 'iri', name: 'Iran',         flag: '🇮🇷', strength: 68 },
  { id: 'gha', name: 'Ghana',        flag: '🇬🇭', strength: 66 },
  { id: 'ksa', name: 'Saudi Arabia', flag: '🇸🇦', strength: 66 },
];
